name: Deploy Container

on:
  workflow_dispatch:

jobs:
  docker:
    name: build docker image and push to repository
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: login to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build image and push to docker hub and gitHub container registry
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: jonaznas/vured-bot:latest
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
